// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSuWuX51DD7yIRKPuCMBw1mfZiezAUfPw',
    appId: '1:20860915607:web:34f50c615ada59ebd33ed2',
    messagingSenderId: '20860915607',
    projectId: 'modswap-7b425',
    authDomain: 'modswap-7b425.firebaseapp.com',
    storageBucket: 'modswap-7b425.firebasestorage.app',
    measurementId: 'G-ZF3WCGR10W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1FuHJS8Ghu9qkoMvBLxhLMmAulRK1mj4',
    appId: '1:20860915607:android:e3b727ae4a6dbfecd33ed2',
    messagingSenderId: '20860915607',
    projectId: 'modswap-7b425',
    storageBucket: 'modswap-7b425.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCABlDGT0OkiFGFBbeONv1kf9re7y5diVc',
    appId: '1:20860915607:ios:805df0759219f8b7d33ed2',
    messagingSenderId: '20860915607',
    projectId: 'modswap-7b425',
    storageBucket: 'modswap-7b425.firebasestorage.app',
    iosBundleId: 'com.example.myFinalApp',
  );

}